source "https://rubygems.org"

gem "rails", "~> 6.1.7"
gem "concurrent-ruby", "1.3.4"
gem "twitter-bootstrap-rails", git: "https://github.com/coppolaf/tb3-rails-50_81"
gem "sprockets-rails"
gem "jquery-rails"
